package TaskApp;

/**
* TaskApp/TaskHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Task.idl
* 2 мая 2019 г. 21:45:56 MSK
*/

public final class TaskHolder implements org.omg.CORBA.portable.Streamable
{
  public TaskApp.Task value = null;

  public TaskHolder ()
  {
  }

  public TaskHolder (TaskApp.Task initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TaskApp.TaskHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TaskApp.TaskHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TaskApp.TaskHelper.type ();
  }

}
