package TaskApp;


/**
* TaskApp/Task.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Task.idl
* 2 мая 2019 г. 21:45:56 MSK
*/

public interface Task extends TaskOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Task
